use std::{
    fmt::Debug,
    sync::{Arc, OnceLock},
};

use ratatui::style::Style;
use serde::{Deserialize, Serialize};

use crate::{
    args::AppTheme,
    tui::themes::{
        aardvark_blue::AardvarkBlue, abernathy::Abernathy, adventure::Adventure,
        adventure_time::AdventureTime, adwaita::Adwaita, adwaita_dark::AdwaitaDark,
        afterglow::Afterglow, alabaster::Alabaster, alien_blood::AlienBlood, andromeda::Andromeda,
        apple_classic::AppleClassic, apple_system_colors::AppleSystemColors,
        apple_system_colors_light::AppleSystemColorsLight, arcoiris::Arcoiris, ardoise::Ardoise,
        argonaut::Argonaut, arthur::Arthur, atelier_sulphurpool::AtelierSulphurpool, atom::Atom,
        atom_one_dark::AtomOneDark, atom_one_light::AtomOneLight, aura::Aura, aurora::Aurora,
        ayu::Ayu, ayu_light::AyuLight, ayu_mirage::AyuMirage, banana_blueberry::BananaBlueberry,
        batman::Batman, belafonte_day::BelafonteDay, belafonte_night::BelafonteNight,
        birds_of_paradise::BirdsOfParadise, black_metal::BlackMetal,
        black_metal_bathory_::BlackMetalBathory, black_metal_burzum_::BlackMetalBurzum,
        black_metal_dark_funeral_::BlackMetalDarkFuneral,
        black_metal_gorgoroth_::BlackMetalGorgoroth, black_metal_immortal_::BlackMetalImmortal,
        black_metal_khold_::BlackMetalKhold, black_metal_marduk_::BlackMetalMarduk,
        black_metal_mayhem_::BlackMetalMayhem, black_metal_nile_::BlackMetalNile,
        black_metal_venom_::BlackMetalVenom, blazer::Blazer, blue_berry_pie::BlueBerryPie,
        blue_dolphin::BlueDolphin, blue_matrix::BlueMatrix, bluloco_dark::BlulocoDark,
        bluloco_light::BlulocoLight, borland::Borland, breadog::Breadog, breeze::Breeze,
        bright_lights::BrightLights, broadcast::Broadcast, brogrammer::Brogrammer,
        builtin_dark::BuiltinDark, builtin_light::BuiltinLight,
        builtin_pastel_dark::BuiltinPastelDark, builtin_solarized_dark::BuiltinSolarizedDark,
        builtin_solarized_light::BuiltinSolarizedLight, builtin_tango_dark::BuiltinTangoDark,
        builtin_tango_light::BuiltinTangoLight, calamity::Calamity, catppuccin::Catppuccin,
        catppuccin_frappe::CatppuccinFrappe, catppuccin_latte::CatppuccinLatte,
        catppuccin_macchiato::CatppuccinMacchiato, catppuccin_mocha::CatppuccinMocha, cga::Cga,
        chakra::Chakra, chalk::Chalk, chalkboard::Chalkboard, challenger_deep::ChallengerDeep,
        chester::Chester, ciapre::Ciapre, citruszest::Citruszest, clrs::Clrs,
        cobalt_neon::CobaltNeon, cobalt_next::CobaltNext, cobalt_next_dark::CobaltNextDark,
        cobalt_next_minimal::CobaltNextMinimal, coffee_theme::CoffeeTheme,
        crayon_pony_fish::CrayonPonyFish, cursor_dark::CursorDark, custom::Custom,
        cutie_pro::CutiePro, cyberdyne::Cyberdyne, cyberpunk::Cyberpunk,
        cyberpunk_scarlet_protocol::CyberpunkScarletProtocol, dark_modern::DarkModern,
        dark_pastel::DarkPastel, darkermatrix::Darkermatrix, darkmatrix::Darkmatrix,
        darkside::Darkside, dayfox::Dayfox, deep::Deep, desert::Desert, detuned::Detuned,
        dimidium::Dimidium, dimmed_monokai::DimmedMonokai, django::Django,
        django_reborn_again::DjangoRebornAgain, django_smooth::DjangoSmooth, doom_one::DoomOne,
        doom_peacock::DoomPeacock, dot_gov::DotGov, dracula::Dracula, duckbones::Duckbones,
        duotone_dark::DuotoneDark, earthsong::Earthsong, electron_highlighter::ElectronHighlighter,
        elegant::Elegant, elemental::Elemental, elementary::Elementary, embark::Embark,
        embers_dark::EmbersDark, encom::Encom, espresso::Espresso, espresso_libre::EspressoLibre,
        everblush::Everblush, everforest_dark_hard::EverforestDarkHard,
        everforest_light_med::EverforestLightMed, fahrenheit::Fahrenheit, fairyfloss::Fairyfloss,
        farmhouse_dark::FarmhouseDark, farmhouse_light::FarmhouseLight, fideloper::Fideloper,
        firefly_traditional::FireflyTraditional, firefox_dev::FirefoxDev, firewatch::Firewatch,
        fish_tank::FishTank, flat::Flat, flatland::Flatland, flexoki_dark::FlexokiDark,
        flexoki_light::FlexokiLight, floraverse::Floraverse, forest_blue::ForestBlue,
        framer::Framer, front_end_delight::FrontEndDelight, fun_forrest::FunForrest,
        galaxy::Galaxy, galizur::Galizur, ghostty_default_style_dark::GhosttyDefaultStyleDark,
        git_hub::Github, git_hub_dark::GithubDark, git_hub_dark_colorblind::GithubDarkColorblind,
        git_hub_dark_default::GithubDarkDefault, git_hub_dark_dimmed::GithubDarkDimmed,
        git_hub_dark_high_contrast::GithubDarkHighContrast,
        git_hub_light_colorblind::GithubLightColorblind, git_hub_light_default::GithubLightDefault,
        git_hub_light_high_contrast::GithubLightHighContrast, git_lab_dark::GitlabDark,
        git_lab_dark_grey::GitlabDarkGrey, git_lab_light::GitlabLight, glacier::Glacier,
        grape::Grape, grass::Grass, grey_green::GreyGreen, gruber_darker::GruberDarker,
        gruvbox_dark::GruvboxDark, gruvbox_dark_hard::GruvboxDarkHard, gruvbox_light::GruvboxLight,
        gruvbox_light_hard::GruvboxLightHard, gruvbox_material::GruvboxMaterial,
        guezwhoz::Guezwhoz, hacktober::Hacktober, hardcore::Hardcore, harper::Harper,
        havn_daggry::HavnDaggry, havn_skumring::HavnSkumring, heeler::Heeler, highway::Highway,
        hipster_green::HipsterGreen, hivacruz::Hivacruz, homebrew::Homebrew, hopscotch::Hopscotch,
        horizon::Horizon, horizon_bright::HorizonBright, hurtado::Hurtado, hybrid::Hybrid,
        ic_green_ppl::IcGreenPpl, ic_orange_ppl::IcOrangePpl, iceberg_dark::IcebergDark,
        iceberg_light::IcebergLight, idea::Idea, idle_toes::IdleToes, ir_black::IrBlack,
        irix_console::IrixConsole, irix_terminal::IrixTerminal, jackie_brown::JackieBrown,
        japanesque::Japanesque, jellybeans::Jellybeans, jet_brains_darcula::JetbrainsDarcula,
        jubi::Jubi, kanagawa_dragon::KanagawaDragon, kanagawa_wave::KanagawaWave,
        kanagawabones::Kanagawabones, kibble::Kibble, kitty_default::KittyDefault,
        kitty_low_contrast::KittyLowContrast, kolorit::Kolorit, konsolas::Konsolas,
        kurokula::Kurokula, lab_fox::LabFox, laser::Laser, later_this_evening::LaterThisEvening,
        lavandula::Lavandula, light_owl::LightOwl, liquid_carbon::LiquidCarbon,
        liquid_carbon_transparent::LiquidCarbonTransparent,
        liquid_carbon_transparent_inverse::LiquidCarbonTransparentInverse, lovelace::Lovelace,
        man_page::ManPage, mariana::Mariana, material::Material, material_dark::MaterialDark,
        material_darker::MaterialDarker, material_design_colors::MaterialDesignColors,
        material_ocean::MaterialOcean, mathias::Mathias, matrix::Matrix, medallion::Medallion,
        melange_dark::MelangeDark, melange_light::MelangeLight, mellifluous::Mellifluous,
        mellow::Mellow, miasma::Miasma, midnight_in_mojave::MidnightInMojave, mirage::Mirage,
        misterioso::Misterioso, molokai::Molokai, mona_lisa::MonaLisa, monokai::Monokai,
        monokai_classic::MonokaiClassic, monokai_pro::MonokaiPro,
        monokai_pro_light::MonokaiProLight, monokai_pro_light_sun::MonokaiProLightSun,
        monokai_pro_machine::MonokaiProMachine, monokai_pro_octagon::MonokaiProOctagon,
        monokai_pro_ristretto::MonokaiProRistretto, monokai_pro_spectrum::MonokaiProSpectrum,
        monokai_remastered::MonokaiRemastered, monokai_soda::MonokaiSoda,
        monokai_vivid::MonokaiVivid, moonfly::Moonfly, neobones_dark::NeobonesDark,
        neobones_light::NeobonesLight, neon::Neon, neopolitan::Neopolitan, neutron::Neutron,
        night_owl::NightOwl, night_owlish_light::NightOwlishLight, nightfox::Nightfox, niji::Niji,
        nocturnal_winter::NocturnalWinter, nord::Nord, nord_light::NordLight, nord_wave::NordWave,
        novel::Novel, nvim_dark::NvimDark, nvim_light::NvimLight, obsidian::Obsidian, ocean::Ocean,
        oceanic_material::OceanicMaterial, oceanic_next::OceanicNext, ollie::Ollie,
        one_double_dark::OneDoubleDark, one_double_light::OneDoubleLight,
        one_half_dark::OneHalfDark, one_half_light::OneHalfLight,
        operator_mono_dark::OperatorMonoDark, overnight_slumber::OvernightSlumber,
        oxocarbon::Oxocarbon, pale_night_hc::PaleNightHc, pandora::Pandora,
        paraiso_dark::ParaisoDark, paul_millr::PaulMillr, pencil_dark::PencilDark,
        pencil_light::PencilLight, peppermint::Peppermint, phala_green_dark::PhalaGreenDark,
        piatto_light::PiattoLight, pnevma::Pnevma, popping_and_locking::PoppingAndLocking,
        powershell::Powershell, primary::Primary, pro::Pro, pro_light::ProLight,
        purple_rain::PurpleRain, purplepeter::Purplepeter, rapture::Rapture,
        raycast_dark::RaycastDark, raycast_light::RaycastLight, rebecca::Rebecca,
        red_alert::RedAlert, red_planet::RedPlanet, red_sands::RedSands, relaxed::Relaxed,
        retro::Retro, retro_legends::RetroLegends, rippedcasts::Rippedcasts, rose_pine::RosePine,
        rose_pine_dawn::RosePineDawn, rose_pine_moon::RosePineMoon, royal::Royal, ryuuko::Ryuuko,
        sakura::Sakura, scarlet_protocol::ScarletProtocol, sea_shells::SeaShells,
        seafoam_pastel::SeafoamPastel, selenized_dark::SelenizedDark,
        selenized_light::SelenizedLight, seoulbones_dark::SeoulbonesDark,
        seoulbones_light::SeoulbonesLight, seti::Seti, shades_of_purple::ShadesOfPurple,
        shaman::Shaman, slate::Slate, sleepy_hollow::SleepyHollow, smyck::Smyck, snazzy::Snazzy,
        snazzy_soft::SnazzySoft, soft_server::SoftServer, solarized_darcula::SolarizedDarcula,
        solarized_dark_higher_contrast::SolarizedDarkHigherContrast,
        solarized_dark_patched::SolarizedDarkPatched, solarized_osaka_night::SolarizedOsakaNight,
        sonokai::Sonokai, spacedust::Spacedust, spacegray::Spacegray,
        spacegray_bright::SpacegrayBright, spacegray_eighties::SpacegrayEighties,
        spacegray_eighties_dull::SpacegrayEightiesDull, spiderman::Spiderman, spring::Spring,
        square::Square, squirrelsong_dark::SquirrelsongDark, srcery::Srcery, starlight::Starlight,
        styler::Styler, sublette::Sublette, subliminal::Subliminal, sugarplum::Sugarplum,
        sundried::Sundried, symfonic::Symfonic, synthwave::Synthwave,
        synthwave_alpha::SynthwaveAlpha, synthwave_everything::SynthwaveEverything,
        tango_adapted::TangoAdapted, tango_half_adapted::TangoHalfAdapted, tearout::Tearout,
        teerb::Teerb, terafox::Terafox, terminal::Terminal, terminal_basic::TerminalBasic,
        terminal_basic_dark::TerminalBasicDark, thayer_bright::ThayerBright, the_hulk::TheHulk,
        tinacious_design_dark::TinaciousDesignDark, tinacious_design_light::TinaciousDesignLight,
        tokyo_night::TokyoNight, tokyo_night_day::TokyoNightDay, tokyo_night_moon::TokyoNightMoon,
        tokyo_night_night::TokyoNightNight, tokyo_night_storm::TokyoNightStorm, tomorrow::Tomorrow,
        tomorrow_night::TomorrowNight, tomorrow_night_blue::TomorrowNightBlue,
        tomorrow_night_bright::TomorrowNightBright, tomorrow_night_burns::TomorrowNightBurns,
        tomorrow_night_eighties::TomorrowNightEighties, toy_chest::ToyChest, treehouse::Treehouse,
        twilight::Twilight, ubuntu::Ubuntu, ultra_dark::UltraDark, ultra_violent::UltraViolent,
        under_the_sea::UnderTheSea, unikitty::Unikitty, urple::Urple, vague::Vague, vaughn::Vaughn,
        vercel::Vercel, vesper::Vesper, vibrant_ink::VibrantInk, vimbones::Vimbones,
        violet_dark::VioletDark, violet_light::VioletLight, violite::Violite, warm_neon::WarmNeon,
        wez::Wez, whimsy::Whimsy, wild_cherry::WildCherry, wilmersdorf::Wilmersdorf,
        wombat::Wombat, wryan::Wryan, xcode_dark::XcodeDark, xcode_dark_hc::XcodeDarkHc,
        xcode_light::XcodeLight, xcode_light_hc::XcodeLightHc, xcode_wwdc::XcodeWwdc,
        zenbones::Zenbones, zenbones_dark::ZenbonesDark, zenbones_light::ZenbonesLight,
        zenburn::Zenburn, zenburned::Zenburned, zenwritten_dark::ZenwrittenDark,
        zenwritten_light::ZenwrittenLight,
    },
};

#[derive(Debug, Clone)]
pub struct Theme {
    styler: Option<Arc<dyn Styler + Send + Sync>>,
}

impl Theme {
    fn new<S: Styler + Send + Sync + 'static>(theme: S) -> Self {
        Theme {
            styler: Some(Arc::new(theme)),
        }
    }

    fn styler(&self) -> Arc<dyn Styler> {
        self.styler.clone().unwrap_or(Arc::new(Monokai))
    }

    pub fn all() -> &'static [Theme] {
        static ALL: OnceLock<Vec<Theme>> = OnceLock::new();
        ALL.get_or_init(|| {
            vec![
                Theme::new(AardvarkBlue),
                Theme::new(Abernathy),
                Theme::new(Adventure),
                Theme::new(AdventureTime),
                Theme::new(Adwaita),
                Theme::new(AdwaitaDark),
                Theme::new(Afterglow),
                Theme::new(Alabaster),
                Theme::new(AlienBlood),
                Theme::new(Andromeda),
                Theme::new(AppleClassic),
                Theme::new(AppleSystemColors),
                Theme::new(AppleSystemColorsLight),
                Theme::new(Arcoiris),
                Theme::new(Ardoise),
                Theme::new(Argonaut),
                Theme::new(Argonaut),
                Theme::new(Arthur),
                Theme::new(AtelierSulphurpool),
                Theme::new(Atom),
                Theme::new(AtomOneDark),
                Theme::new(AtomOneLight),
                Theme::new(Aura),
                Theme::new(Aurora),
                Theme::new(Ayu),
                Theme::new(AyuLight),
                Theme::new(AyuMirage),
                Theme::new(BananaBlueberry),
                Theme::new(Batman),
                Theme::new(BelafonteDay),
                Theme::new(BelafonteNight),
                Theme::new(BirdsOfParadise),
                Theme::new(BlackMetal),
                Theme::new(BlackMetalBathory),
                Theme::new(BlackMetalBurzum),
                Theme::new(BlackMetalDarkFuneral),
                Theme::new(BlackMetalGorgoroth),
                Theme::new(BlackMetalImmortal),
                Theme::new(BlackMetalKhold),
                Theme::new(BlackMetalMarduk),
                Theme::new(BlackMetalMayhem),
                Theme::new(BlackMetalNile),
                Theme::new(BlackMetalVenom),
                Theme::new(Blazer),
                Theme::new(BlueBerryPie),
                Theme::new(BlueDolphin),
                Theme::new(BlueMatrix),
                Theme::new(BlulocoDark),
                Theme::new(BlulocoLight),
                Theme::new(Borland),
                Theme::new(Breadog),
                Theme::new(Breeze),
                Theme::new(BrightLights),
                Theme::new(Broadcast),
                Theme::new(Brogrammer),
                Theme::new(BuiltinDark),
                Theme::new(BuiltinLight),
                Theme::new(BuiltinPastelDark),
                Theme::new(BuiltinSolarizedDark),
                Theme::new(BuiltinSolarizedLight),
                Theme::new(BuiltinTangoDark),
                Theme::new(BuiltinTangoLight),
                Theme::new(Calamity),
                Theme::new(Catppuccin),
                Theme::new(CatppuccinFrappe),
                Theme::new(CatppuccinLatte),
                Theme::new(CatppuccinMacchiato),
                Theme::new(CatppuccinMocha),
                Theme::new(Cga),
                Theme::new(Chakra),
                Theme::new(Chalk),
                Theme::new(Chalkboard),
                Theme::new(ChallengerDeep),
                Theme::new(Chester),
                Theme::new(Ciapre),
                Theme::new(Citruszest),
                Theme::new(Clrs),
                Theme::new(CobaltNeon),
                Theme::new(CobaltNext),
                Theme::new(CobaltNextDark),
                Theme::new(CobaltNextMinimal),
                Theme::new(CoffeeTheme),
                Theme::new(CrayonPonyFish),
                Theme::new(CursorDark),
                Theme::new(Custom::default()),
                Theme::new(CutiePro),
                Theme::new(Cyberdyne),
                Theme::new(Cyberpunk),
                Theme::new(CyberpunkScarletProtocol),
                Theme::new(DarkModern),
                Theme::new(DarkPastel),
                Theme::new(Darkermatrix),
                Theme::new(Darkmatrix),
                Theme::new(Darkside),
                Theme::new(Dayfox),
                Theme::new(Deep),
                Theme::new(Desert),
                Theme::new(Detuned),
                Theme::new(Dimidium),
                Theme::new(DimmedMonokai),
                Theme::new(Django),
                Theme::new(DjangoRebornAgain),
                Theme::new(DjangoSmooth),
                Theme::new(DoomOne),
                Theme::new(DoomPeacock),
                Theme::new(DotGov),
                Theme::new(Dracula),
                Theme::new(Duckbones),
                Theme::new(DuotoneDark),
                Theme::new(Earthsong),
                Theme::new(ElectronHighlighter),
                Theme::new(Elegant),
                Theme::new(Elemental),
                Theme::new(Elementary),
                Theme::new(Embark),
                Theme::new(EmbersDark),
                Theme::new(Encom),
                Theme::new(Espresso),
                Theme::new(EspressoLibre),
                Theme::new(Everblush),
                Theme::new(EverforestDarkHard),
                Theme::new(EverforestLightMed),
                Theme::new(Fahrenheit),
                Theme::new(Fairyfloss),
                Theme::new(FarmhouseDark),
                Theme::new(FarmhouseLight),
                Theme::new(Fideloper),
                Theme::new(FireflyTraditional),
                Theme::new(FirefoxDev),
                Theme::new(Firewatch),
                Theme::new(FishTank),
                Theme::new(Flat),
                Theme::new(Flatland),
                Theme::new(FlexokiDark),
                Theme::new(FlexokiLight),
                Theme::new(Floraverse),
                Theme::new(ForestBlue),
                Theme::new(Framer),
                Theme::new(FrontEndDelight),
                Theme::new(FunForrest),
                Theme::new(Galaxy),
                Theme::new(Galizur),
                Theme::new(GhosttyDefaultStyleDark),
                Theme::new(Github),
                Theme::new(GithubDark),
                Theme::new(GithubDarkColorblind),
                Theme::new(GithubDarkDefault),
                Theme::new(GithubDarkDimmed),
                Theme::new(GithubDarkHighContrast),
                Theme::new(GithubLightColorblind),
                Theme::new(GithubLightDefault),
                Theme::new(GithubLightHighContrast),
                Theme::new(GitlabDark),
                Theme::new(GitlabDarkGrey),
                Theme::new(GitlabLight),
                Theme::new(Glacier),
                Theme::new(Grape),
                Theme::new(Grass),
                Theme::new(GreyGreen),
                Theme::new(GruberDarker),
                Theme::new(GruvboxDark),
                Theme::new(GruvboxDarkHard),
                Theme::new(GruvboxLight),
                Theme::new(GruvboxLightHard),
                Theme::new(GruvboxMaterial),
                Theme::new(Guezwhoz),
                Theme::new(Hacktober),
                Theme::new(Hardcore),
                Theme::new(Harper),
                Theme::new(HavnDaggry),
                Theme::new(HavnSkumring),
                Theme::new(Heeler),
                Theme::new(Highway),
                Theme::new(HipsterGreen),
                Theme::new(Hivacruz),
                Theme::new(Homebrew),
                Theme::new(Hopscotch),
                Theme::new(Horizon),
                Theme::new(HorizonBright),
                Theme::new(Hurtado),
                Theme::new(Hybrid),
                Theme::new(IcGreenPpl),
                Theme::new(IcOrangePpl),
                Theme::new(IcebergDark),
                Theme::new(IcebergLight),
                Theme::new(Idea),
                Theme::new(IdleToes),
                Theme::new(IrBlack),
                Theme::new(IrixConsole),
                Theme::new(IrixTerminal),
                Theme::new(JackieBrown),
                Theme::new(Japanesque),
                Theme::new(Jellybeans),
                Theme::new(JetbrainsDarcula),
                Theme::new(Jubi),
                Theme::new(KanagawaDragon),
                Theme::new(KanagawaWave),
                Theme::new(Kanagawabones),
                Theme::new(Kibble),
                Theme::new(KittyDefault),
                Theme::new(KittyLowContrast),
                Theme::new(Kolorit),
                Theme::new(Konsolas),
                Theme::new(Kurokula),
                Theme::new(LabFox),
                Theme::new(Laser),
                Theme::new(LaterThisEvening),
                Theme::new(Lavandula),
                Theme::new(LightOwl),
                Theme::new(LiquidCarbon),
                Theme::new(LiquidCarbonTransparent),
                Theme::new(LiquidCarbonTransparentInverse),
                Theme::new(Lovelace),
                Theme::new(ManPage),
                Theme::new(Mariana),
                Theme::new(Material),
                Theme::new(MaterialDark),
                Theme::new(MaterialDarker),
                Theme::new(MaterialDesignColors),
                Theme::new(MaterialOcean),
                Theme::new(Mathias),
                Theme::new(Matrix),
                Theme::new(Medallion),
                Theme::new(MelangeDark),
                Theme::new(MelangeLight),
                Theme::new(Mellifluous),
                Theme::new(Mellow),
                Theme::new(Miasma),
                Theme::new(MidnightInMojave),
                Theme::new(Mirage),
                Theme::new(Misterioso),
                Theme::new(Molokai),
                Theme::new(MonaLisa),
                Theme::new(Monokai),
                Theme::new(MonokaiClassic),
                Theme::new(MonokaiPro),
                Theme::new(MonokaiProLight),
                Theme::new(MonokaiProLightSun),
                Theme::new(MonokaiProMachine),
                Theme::new(MonokaiProOctagon),
                Theme::new(MonokaiProRistretto),
                Theme::new(MonokaiProSpectrum),
                Theme::new(MonokaiRemastered),
                Theme::new(MonokaiSoda),
                Theme::new(MonokaiVivid),
                Theme::new(Moonfly),
                Theme::new(NeobonesDark),
                Theme::new(NeobonesLight),
                Theme::new(Neon),
                Theme::new(Neopolitan),
                Theme::new(Neutron),
                Theme::new(NightOwl),
                Theme::new(NightOwlishLight),
                Theme::new(Nightfox),
                Theme::new(Niji),
                Theme::new(NocturnalWinter),
                Theme::new(Nord),
                Theme::new(Nord),
                Theme::new(NordLight),
                Theme::new(NordWave),
                Theme::new(Novel),
                Theme::new(NvimDark),
                Theme::new(NvimLight),
                Theme::new(Obsidian),
                Theme::new(Ocean),
                Theme::new(OceanicMaterial),
                Theme::new(OceanicNext),
                Theme::new(Ollie),
                Theme::new(OneDoubleDark),
                Theme::new(OneDoubleLight),
                Theme::new(OneHalfDark),
                Theme::new(OneHalfLight),
                Theme::new(OperatorMonoDark),
                Theme::new(OvernightSlumber),
                Theme::new(Oxocarbon),
                Theme::new(PaleNightHc),
                Theme::new(Pandora),
                Theme::new(ParaisoDark),
                Theme::new(PaulMillr),
                Theme::new(PencilDark),
                Theme::new(PencilLight),
                Theme::new(Peppermint),
                Theme::new(PhalaGreenDark),
                Theme::new(PiattoLight),
                Theme::new(Pnevma),
                Theme::new(PoppingAndLocking),
                Theme::new(Powershell),
                Theme::new(Primary),
                Theme::new(Pro),
                Theme::new(ProLight),
                Theme::new(PurpleRain),
                Theme::new(Purplepeter),
                Theme::new(Rapture),
                Theme::new(RaycastDark),
                Theme::new(RaycastLight),
                Theme::new(Rebecca),
                Theme::new(RedAlert),
                Theme::new(RedPlanet),
                Theme::new(RedSands),
                Theme::new(Relaxed),
                Theme::new(Retro),
                Theme::new(RetroLegends),
                Theme::new(Rippedcasts),
                Theme::new(RosePine),
                Theme::new(RosePineDawn),
                Theme::new(RosePineMoon),
                Theme::new(Royal),
                Theme::new(Ryuuko),
                Theme::new(Sakura),
                Theme::new(ScarletProtocol),
                Theme::new(SeaShells),
                Theme::new(SeafoamPastel),
                Theme::new(SelenizedDark),
                Theme::new(SelenizedLight),
                Theme::new(SeoulbonesDark),
                Theme::new(SeoulbonesLight),
                Theme::new(Seti),
                Theme::new(ShadesOfPurple),
                Theme::new(Shaman),
                Theme::new(Slate),
                Theme::new(SleepyHollow),
                Theme::new(Smyck),
                Theme::new(Snazzy),
                Theme::new(SnazzySoft),
                Theme::new(SoftServer),
                Theme::new(SolarizedDarcula),
                Theme::new(SolarizedDarkHigherContrast),
                Theme::new(SolarizedDarkPatched),
                Theme::new(SolarizedOsakaNight),
                Theme::new(Sonokai),
                Theme::new(Spacedust),
                Theme::new(Spacegray),
                Theme::new(SpacegrayBright),
                Theme::new(SpacegrayEighties),
                Theme::new(SpacegrayEightiesDull),
                Theme::new(Spiderman),
                Theme::new(Spring),
                Theme::new(Square),
                Theme::new(SquirrelsongDark),
                Theme::new(Srcery),
                Theme::new(Starlight),
                Theme::new(Sublette),
                Theme::new(Subliminal),
                Theme::new(Sugarplum),
                Theme::new(Sundried),
                Theme::new(Symfonic),
                Theme::new(Synthwave),
                Theme::new(SynthwaveAlpha),
                Theme::new(SynthwaveEverything),
                Theme::new(TangoAdapted),
                Theme::new(TangoHalfAdapted),
                Theme::new(Tearout),
                Theme::new(Teerb),
                Theme::new(Terafox),
                Theme::new(Terminal),
                Theme::new(TerminalBasic),
                Theme::new(TerminalBasicDark),
                Theme::new(ThayerBright),
                Theme::new(TheHulk),
                Theme::new(TinaciousDesignDark),
                Theme::new(TinaciousDesignLight),
                Theme::new(TokyoNight),
                Theme::new(TokyoNightDay),
                Theme::new(TokyoNightMoon),
                Theme::new(TokyoNightNight),
                Theme::new(TokyoNightStorm),
                Theme::new(Tomorrow),
                Theme::new(TomorrowNight),
                Theme::new(TomorrowNightBlue),
                Theme::new(TomorrowNightBright),
                Theme::new(TomorrowNightBurns),
                Theme::new(TomorrowNightEighties),
                Theme::new(ToyChest),
                Theme::new(Treehouse),
                Theme::new(Twilight),
                Theme::new(Ubuntu),
                Theme::new(UltraDark),
                Theme::new(UltraViolent),
                Theme::new(UnderTheSea),
                Theme::new(Unikitty),
                Theme::new(Urple),
                Theme::new(Vague),
                Theme::new(Vaughn),
                Theme::new(Vercel),
                Theme::new(Vesper),
                Theme::new(VibrantInk),
                Theme::new(Vimbones),
                Theme::new(VioletDark),
                Theme::new(VioletLight),
                Theme::new(Violite),
                Theme::new(WarmNeon),
                Theme::new(Wez),
                Theme::new(Whimsy),
                Theme::new(WildCherry),
                Theme::new(Wilmersdorf),
                Theme::new(Wombat),
                Theme::new(Wryan),
                Theme::new(XcodeDark),
                Theme::new(XcodeDarkHc),
                Theme::new(XcodeLight),
                Theme::new(XcodeLightHc),
                Theme::new(XcodeWwdc),
                Theme::new(Zenbones),
                Theme::new(ZenbonesDark),
                Theme::new(ZenbonesLight),
                Theme::new(Zenburn),
                Theme::new(Zenburned),
                Theme::new(ZenwrittenDark),
                Theme::new(ZenwrittenLight),
            ]
        })
    }

    pub const fn default() -> Self {
        Self { styler: None }
    }
}

impl From<AppTheme> for Theme {
    fn from(value: AppTheme) -> Self {
        match value {
            AppTheme::MonokaiProLightSun => Theme::new(MonokaiProLightSun),
            AppTheme::BlackMetalImmortal => Theme::new(BlackMetalImmortal),
            AppTheme::Starlight => Theme::new(Starlight),
            AppTheme::AyuLight => Theme::new(AyuLight),
            AppTheme::BuiltinTangoLight => Theme::new(BuiltinTangoLight),
            AppTheme::NvimLight => Theme::new(NvimLight),
            AppTheme::Twilight => Theme::new(Twilight),
            AppTheme::Hybrid => Theme::new(Hybrid),
            AppTheme::Lovelace => Theme::new(Lovelace),
            AppTheme::Spring => Theme::new(Spring),
            AppTheme::ZenwrittenDark => Theme::new(ZenwrittenDark),
            AppTheme::Neopolitan => Theme::new(Neopolitan),
            AppTheme::Ciapre => Theme::new(Ciapre),
            AppTheme::Sublette => Theme::new(Sublette),
            AppTheme::ManPage => Theme::new(ManPage),
            AppTheme::Purplepeter => Theme::new(Purplepeter),
            AppTheme::Breadog => Theme::new(Breadog),
            AppTheme::LightOwl => Theme::new(LightOwl),
            AppTheme::Galizur => Theme::new(Galizur),
            AppTheme::RosePine => Theme::new(RosePine),
            AppTheme::Molokai => Theme::new(Molokai),
            AppTheme::Shaman => Theme::new(Shaman),
            AppTheme::Darkermatrix => Theme::new(Darkermatrix),
            AppTheme::JackieBrown => Theme::new(JackieBrown),
            AppTheme::Espresso => Theme::new(Espresso),
            AppTheme::Peppermint => Theme::new(Peppermint),
            AppTheme::UltraViolent => Theme::new(UltraViolent),
            AppTheme::Primary => Theme::new(Primary),
            AppTheme::NvimDark => Theme::new(NvimDark),
            AppTheme::RetroLegends => Theme::new(RetroLegends),
            AppTheme::IcebergDark => Theme::new(IcebergDark),
            AppTheme::MonokaiRemastered => Theme::new(MonokaiRemastered),
            AppTheme::DotGov => Theme::new(DotGov),
            AppTheme::OceanicNext => Theme::new(OceanicNext),
            AppTheme::Material => Theme::new(Material),
            AppTheme::BlackMetalMarduk => Theme::new(BlackMetalMarduk),
            AppTheme::GreyGreen => Theme::new(GreyGreen),
            AppTheme::Broadcast => Theme::new(Broadcast),
            AppTheme::Matrix => Theme::new(Matrix),
            AppTheme::OneDoubleLight => Theme::new(OneDoubleLight),
            AppTheme::ElectronHighlighter => Theme::new(ElectronHighlighter),
            AppTheme::Ubuntu => Theme::new(Ubuntu),
            AppTheme::Clrs => Theme::new(Clrs),
            AppTheme::TomorrowNightBlue => Theme::new(TomorrowNightBlue),
            AppTheme::Django => Theme::new(Django),
            AppTheme::Brogrammer => Theme::new(Brogrammer),
            AppTheme::Mellow => Theme::new(Mellow),
            AppTheme::JetbrainsDarcula => Theme::new(JetbrainsDarcula),
            AppTheme::MonokaiVivid => Theme::new(MonokaiVivid),
            AppTheme::Fideloper => Theme::new(Fideloper),
            AppTheme::FarmhouseDark => Theme::new(FarmhouseDark),
            AppTheme::Royal => Theme::new(Royal),
            AppTheme::GruvboxLight => Theme::new(GruvboxLight),
            AppTheme::GruvboxDark => Theme::new(GruvboxDark),
            AppTheme::Smyck => Theme::new(Smyck),
            AppTheme::Pnevma => Theme::new(Pnevma),
            AppTheme::BlackMetalNile => Theme::new(BlackMetalNile),
            AppTheme::Elementary => Theme::new(Elementary),
            AppTheme::SquirrelsongDark => Theme::new(SquirrelsongDark),
            AppTheme::CatppuccinMocha => Theme::new(CatppuccinMocha),
            AppTheme::BlackMetalBathory => Theme::new(BlackMetalBathory),
            AppTheme::LiquidCarbonTransparentInverse => Theme::new(LiquidCarbonTransparentInverse),
            AppTheme::FunForrest => Theme::new(FunForrest),
            AppTheme::Arcoiris => Theme::new(Arcoiris),
            AppTheme::Desert => Theme::new(Desert),
            AppTheme::DoomOne => Theme::new(DoomOne),
            AppTheme::SpacegrayEighties => Theme::new(SpacegrayEighties),
            AppTheme::WarmNeon => Theme::new(WarmNeon),
            AppTheme::Dimidium => Theme::new(Dimidium),
            AppTheme::GitlabDarkGrey => Theme::new(GitlabDarkGrey),
            AppTheme::Cyberpunk => Theme::new(Cyberpunk),
            AppTheme::Tearout => Theme::new(Tearout),
            AppTheme::Aura => Theme::new(Aura),
            AppTheme::Grape => Theme::new(Grape),
            AppTheme::SelenizedLight => Theme::new(SelenizedLight),
            AppTheme::Blazer => Theme::new(Blazer),
            AppTheme::KanagawaDragon => Theme::new(KanagawaDragon),
            AppTheme::Hurtado => Theme::new(Hurtado),
            AppTheme::MaterialOcean => Theme::new(MaterialOcean),
            AppTheme::XcodeDarkHc => Theme::new(XcodeDarkHc),
            AppTheme::Citruszest => Theme::new(Citruszest),
            AppTheme::CrayonPonyFish => Theme::new(CrayonPonyFish),
            AppTheme::Relaxed => Theme::new(Relaxed),
            AppTheme::Rapture => Theme::new(Rapture),
            AppTheme::BlackMetalGorgoroth => Theme::new(BlackMetalGorgoroth),
            AppTheme::Cyberdyne => Theme::new(Cyberdyne),
            AppTheme::GitlabLight => Theme::new(GitlabLight),
            AppTheme::IcebergLight => Theme::new(IcebergLight),
            AppTheme::Floraverse => Theme::new(Floraverse),
            AppTheme::AtomOneDark => Theme::new(AtomOneDark),
            AppTheme::ShadesOfPurple => Theme::new(ShadesOfPurple),
            AppTheme::Wez => Theme::new(Wez),
            AppTheme::AyuMirage => Theme::new(AyuMirage),
            AppTheme::Obsidian => Theme::new(Obsidian),
            AppTheme::Kolorit => Theme::new(Kolorit),
            AppTheme::Hivacruz => Theme::new(Hivacruz),
            AppTheme::AdwaitaDark => Theme::new(AdwaitaDark),
            AppTheme::PencilLight => Theme::new(PencilLight),
            AppTheme::BlulocoDark => Theme::new(BlulocoDark),
            AppTheme::BuiltinTangoDark => Theme::new(BuiltinTangoDark),
            AppTheme::BelafonteDay => Theme::new(BelafonteDay),
            AppTheme::BlueDolphin => Theme::new(BlueDolphin),
            AppTheme::MonokaiPro => Theme::new(MonokaiPro),
            AppTheme::TheHulk => Theme::new(TheHulk),
            AppTheme::Synthwave => Theme::new(Synthwave),
            AppTheme::Konsolas => Theme::new(Konsolas),
            AppTheme::Dayfox => Theme::new(Dayfox),
            AppTheme::SolarizedDarcula => Theme::new(SolarizedDarcula),
            AppTheme::NordWave => Theme::new(NordWave),
            AppTheme::Urple => Theme::new(Urple),
            AppTheme::XcodeLightHc => Theme::new(XcodeLightHc),
            AppTheme::TokyonightNight => Theme::new(TokyoNightNight),
            AppTheme::SynthwaveAlpha => Theme::new(SynthwaveAlpha),
            AppTheme::EspressoLibre => Theme::new(EspressoLibre),
            AppTheme::GithubDarkDefault => Theme::new(GithubDarkDefault),
            AppTheme::Breeze => Theme::new(Breeze),
            AppTheme::Fahrenheit => Theme::new(Fahrenheit),
            AppTheme::CatppuccinLatte => Theme::new(CatppuccinLatte),
            AppTheme::Miasma => Theme::new(Miasma),
            AppTheme::EverforestDarkHard => Theme::new(EverforestDarkHard),
            AppTheme::Seti => Theme::new(Seti),
            AppTheme::BlackMetalDarkFuneral => Theme::new(BlackMetalDarkFuneral),
            AppTheme::Zenburned => Theme::new(Zenburned),
            AppTheme::CobaltNextDark => Theme::new(CobaltNextDark),
            AppTheme::DjangoRebornAgain => Theme::new(DjangoRebornAgain),
            AppTheme::Treehouse => Theme::new(Treehouse),
            AppTheme::Mariana => Theme::new(Mariana),
            AppTheme::Retro => Theme::new(Retro),
            AppTheme::CursorDark => Theme::new(CursorDark),
            AppTheme::Hardcore => Theme::new(Hardcore),
            AppTheme::Neon => Theme::new(Neon),
            AppTheme::GitlabDark => Theme::new(GitlabDark),
            AppTheme::UnderTheSea => Theme::new(UnderTheSea),
            AppTheme::VioletLight => Theme::new(VioletLight),
            AppTheme::Ayu => Theme::new(Ayu),
            AppTheme::HavnSkumring => Theme::new(HavnSkumring),
            AppTheme::Afterglow => Theme::new(Afterglow),
            AppTheme::DoomPeacock => Theme::new(DoomPeacock),
            AppTheme::AppleClassic => Theme::new(AppleClassic),
            AppTheme::VibrantInk => Theme::new(VibrantInk),
            AppTheme::Arthur => Theme::new(Arthur),
            AppTheme::TinaciousDesignLight => Theme::new(TinaciousDesignLight),
            AppTheme::WildCherry => Theme::new(WildCherry),
            AppTheme::HipsterGreen => Theme::new(HipsterGreen),
            AppTheme::Mathias => Theme::new(Mathias),
            AppTheme::NeobonesDark => Theme::new(NeobonesDark),
            AppTheme::SpacegrayEightiesDull => Theme::new(SpacegrayEightiesDull),
            AppTheme::NightOwlishLight => Theme::new(NightOwlishLight),
            AppTheme::Chester => Theme::new(Chester),
            AppTheme::Pandora => Theme::new(Pandora),
            AppTheme::GhosttyDefaultStyleDark => Theme::new(GhosttyDefaultStyleDark),
            AppTheme::OneDoubleDark => Theme::new(OneDoubleDark),
            AppTheme::ZenbonesLight => Theme::new(ZenbonesLight),
            AppTheme::Niji => Theme::new(Niji),
            AppTheme::ProLight => Theme::new(ProLight),
            AppTheme::SpacegrayBright => Theme::new(SpacegrayBright),
            AppTheme::SeaShells => Theme::new(SeaShells),
            AppTheme::Vague => Theme::new(Vague),
            AppTheme::TokyonightMoon => Theme::new(TokyoNightMoon),
            AppTheme::XcodeLight => Theme::new(XcodeLight),
            AppTheme::AardvarkBlue => Theme::new(AardvarkBlue),
            AppTheme::ZenwrittenLight => Theme::new(ZenwrittenLight),
            AppTheme::CobaltNeon => Theme::new(CobaltNeon),
            AppTheme::DuotoneDark => Theme::new(DuotoneDark),
            AppTheme::Cga => Theme::new(Cga),
            AppTheme::Idea => Theme::new(Idea),
            AppTheme::SynthwaveEverything => Theme::new(SynthwaveEverything),
            AppTheme::BlackMetal => Theme::new(BlackMetal),
            AppTheme::HavnDaggry => Theme::new(HavnDaggry),
            AppTheme::Github => Theme::new(Github),
            AppTheme::SeafoamPastel => Theme::new(SeafoamPastel),
            AppTheme::Chalkboard => Theme::new(Chalkboard),
            AppTheme::Elemental => Theme::new(Elemental),
            AppTheme::Novel => Theme::new(Novel),
            AppTheme::Snazzy => Theme::new(Snazzy),
            AppTheme::MonokaiClassic => Theme::new(MonokaiClassic),
            AppTheme::Zenburn => Theme::new(Zenburn),
            AppTheme::GithubLightDefault => Theme::new(GithubLightDefault),
            AppTheme::Laser => Theme::new(Laser),
            AppTheme::BirdsOfParadise => Theme::new(BirdsOfParadise),
            AppTheme::Mellifluous => Theme::new(Mellifluous),
            AppTheme::Fairyfloss => Theme::new(Fairyfloss),
            AppTheme::NightOwl => Theme::new(NightOwl),
            AppTheme::OneHalfDark => Theme::new(OneHalfDark),
            AppTheme::FireflyTraditional => Theme::new(FireflyTraditional),
            AppTheme::Terafox => Theme::new(Terafox),
            AppTheme::RosePineDawn => Theme::new(RosePineDawn),
            AppTheme::Sundried => Theme::new(Sundried),
            AppTheme::TokyonightStorm => Theme::new(TokyoNightStorm),
            AppTheme::Nord => Theme::new(Nord),
            AppTheme::PiattoLight => Theme::new(PiattoLight),
            AppTheme::Abernathy => Theme::new(Abernathy),
            AppTheme::TokyonightDay => Theme::new(TokyoNightDay),
            AppTheme::Powershell => Theme::new(Powershell),
            AppTheme::Jellybeans => Theme::new(Jellybeans),
            AppTheme::BlueMatrix => Theme::new(BlueMatrix),
            AppTheme::Sonokai => Theme::new(Sonokai),
            AppTheme::TomorrowNightBurns => Theme::new(TomorrowNightBurns),
            AppTheme::Sakura => Theme::new(Sakura),
            AppTheme::RaycastDark => Theme::new(RaycastDark),
            AppTheme::KanagawaWave => Theme::new(KanagawaWave),
            AppTheme::CutiePro => Theme::new(CutiePro),
            AppTheme::Horizon => Theme::new(Horizon),
            AppTheme::Spiderman => Theme::new(Spiderman),
            AppTheme::BlackMetalMayhem => Theme::new(BlackMetalMayhem),
            AppTheme::KittyDefault => Theme::new(KittyDefault),
            AppTheme::IdleToes => Theme::new(IdleToes),
            AppTheme::TerminalBasicDark => Theme::new(TerminalBasicDark),
            AppTheme::Framer => Theme::new(Framer),
            AppTheme::Moonfly => Theme::new(Moonfly),
            AppTheme::MonokaiSoda => Theme::new(MonokaiSoda),
            AppTheme::Slate => Theme::new(Slate),
            AppTheme::Firewatch => Theme::new(Firewatch),
            AppTheme::Spacegray => Theme::new(Spacegray),
            AppTheme::Symfonic => Theme::new(Symfonic),
            AppTheme::Spacedust => Theme::new(Spacedust),
            AppTheme::Teerb => Theme::new(Teerb),
            AppTheme::Rippedcasts => Theme::new(Rippedcasts),
            AppTheme::TomorrowNightBright => Theme::new(TomorrowNightBright),
            AppTheme::Chalk => Theme::new(Chalk),
            AppTheme::Heeler => Theme::new(Heeler),
            AppTheme::Alabaster => Theme::new(Alabaster),
            AppTheme::Galaxy => Theme::new(Galaxy),
            AppTheme::Adventure => Theme::new(Adventure),
            AppTheme::GithubLightHighContrast => Theme::new(GithubLightHighContrast),
            AppTheme::Unikitty => Theme::new(Unikitty),
            AppTheme::Lavandula => Theme::new(Lavandula),
            AppTheme::TinaciousDesignDark => Theme::new(TinaciousDesignDark),
            AppTheme::Flatland => Theme::new(Flatland),
            AppTheme::GithubLightColorblind => Theme::new(GithubLightColorblind),
            AppTheme::ChallengerDeep => Theme::new(ChallengerDeep),
            AppTheme::Mirage => Theme::new(Mirage),
            AppTheme::Deep => Theme::new(Deep),
            AppTheme::Vesper => Theme::new(Vesper),
            AppTheme::Aurora => Theme::new(Aurora),
            AppTheme::Jubi => Theme::new(Jubi),
            AppTheme::Calamity => Theme::new(Calamity),
            AppTheme::Neutron => Theme::new(Neutron),
            AppTheme::RedAlert => Theme::new(RedAlert),
            AppTheme::MaterialDark => Theme::new(MaterialDark),
            AppTheme::Everblush => Theme::new(Everblush),
            AppTheme::Kurokula => Theme::new(Kurokula),
            AppTheme::SolarizedOsakaNight => Theme::new(SolarizedOsakaNight),
            AppTheme::PaleNightHc => Theme::new(PaleNightHc),
            AppTheme::Ardoise => Theme::new(Ardoise),
            AppTheme::MonokaiProSpectrum => Theme::new(MonokaiProSpectrum),
            AppTheme::GruberDarker => Theme::new(GruberDarker),
            AppTheme::GithubDark => Theme::new(GithubDark),
            AppTheme::SolarizedDarkPatched => Theme::new(SolarizedDarkPatched),
            AppTheme::MelangeLight => Theme::new(MelangeLight),
            AppTheme::Hacktober => Theme::new(Hacktober),
            AppTheme::IcGreenPpl => Theme::new(IcGreenPpl),
            AppTheme::OperatorMonoDark => Theme::new(OperatorMonoDark),
            AppTheme::TomorrowNight => Theme::new(TomorrowNight),
            AppTheme::Homebrew => Theme::new(Homebrew),
            AppTheme::Wryan => Theme::new(Wryan),
            AppTheme::GithubDarkColorblind => Theme::new(GithubDarkColorblind),
            AppTheme::Borland => Theme::new(Borland),
            AppTheme::RedSands => Theme::new(RedSands),
            AppTheme::Rebecca => Theme::new(Rebecca),
            AppTheme::TerminalBasic => Theme::new(TerminalBasic),
            AppTheme::Dracula => Theme::new(Dracula),
            AppTheme::Nightfox => Theme::new(Nightfox),
            AppTheme::BuiltinLight => Theme::new(BuiltinLight),
            AppTheme::BuiltinSolarizedLight => Theme::new(BuiltinSolarizedLight),
            AppTheme::Glacier => Theme::new(Glacier),
            AppTheme::CatppuccinFrappe => Theme::new(CatppuccinFrappe),
            AppTheme::ForestBlue => Theme::new(ForestBlue),
            AppTheme::BuiltinDark => Theme::new(BuiltinDark),
            AppTheme::Whimsy => Theme::new(Whimsy),
            AppTheme::XcodeDark => Theme::new(XcodeDark),
            AppTheme::GruvboxDarkHard => Theme::new(GruvboxDarkHard),
            AppTheme::Ryuuko => Theme::new(Ryuuko),
            AppTheme::DjangoSmooth => Theme::new(DjangoSmooth),
            AppTheme::VioletDark => Theme::new(VioletDark),
            AppTheme::PurpleRain => Theme::new(PurpleRain),
            AppTheme::Square => Theme::new(Square),
            AppTheme::SeoulbonesDark => Theme::new(SeoulbonesDark),
            AppTheme::DarkModern => Theme::new(DarkModern),
            AppTheme::MonokaiProRistretto => Theme::new(MonokaiProRistretto),
            AppTheme::IrixConsole => Theme::new(IrixConsole),
            AppTheme::MelangeDark => Theme::new(MelangeDark),
            AppTheme::Earthsong => Theme::new(Earthsong),
            AppTheme::LiquidCarbon => Theme::new(LiquidCarbon),
            AppTheme::GruvboxLightHard => Theme::new(GruvboxLightHard),
            AppTheme::AdventureTime => Theme::new(AdventureTime),
            AppTheme::PhalaGreenDark => Theme::new(PhalaGreenDark),
            AppTheme::SoftServer => Theme::new(SoftServer),
            AppTheme::PencilDark => Theme::new(PencilDark),
            AppTheme::FrontEndDelight => Theme::new(FrontEndDelight),
            AppTheme::Grass => Theme::new(Grass),
            AppTheme::Ollie => Theme::new(Ollie),
            AppTheme::MidnightInMojave => Theme::new(MidnightInMojave),
            AppTheme::Highway => Theme::new(Highway),
            AppTheme::OvernightSlumber => Theme::new(OvernightSlumber),
            AppTheme::BelafonteNight => Theme::new(BelafonteNight),
            AppTheme::TangoAdapted => Theme::new(TangoAdapted),
            AppTheme::BlueBerryPie => Theme::new(BlueBerryPie),
            AppTheme::Tomorrow => Theme::new(Tomorrow),
            AppTheme::ScarletProtocol => Theme::new(ScarletProtocol),
            AppTheme::KittyLowContrast => Theme::new(KittyLowContrast),
            AppTheme::OceanicMaterial => Theme::new(OceanicMaterial),
            AppTheme::Guezwhoz => Theme::new(Guezwhoz),
            AppTheme::XcodeWwdc => Theme::new(XcodeWwdc),
            AppTheme::ToyChest => Theme::new(ToyChest),
            AppTheme::PoppingAndLocking => Theme::new(PoppingAndLocking),
            AppTheme::NeobonesLight => Theme::new(NeobonesLight),
            AppTheme::AtelierSulphurpool => Theme::new(AtelierSulphurpool),
            AppTheme::CobaltNext => Theme::new(CobaltNext),
            AppTheme::Atom => Theme::new(Atom),
            AppTheme::ZenbonesDark => Theme::new(ZenbonesDark),
            AppTheme::Zenbones => Theme::new(Zenbones),
            AppTheme::BrightLights => Theme::new(BrightLights),
            AppTheme::GithubDarkHighContrast => Theme::new(GithubDarkHighContrast),
            AppTheme::PaulMillr => Theme::new(PaulMillr),
            AppTheme::NocturnalWinter => Theme::new(NocturnalWinter),
            AppTheme::LabFox => Theme::new(LabFox),
            AppTheme::GithubDarkDimmed => Theme::new(GithubDarkDimmed),
            AppTheme::Detuned => Theme::new(Detuned),
            AppTheme::Misterioso => Theme::new(Misterioso),
            AppTheme::BlackMetalKhold => Theme::new(BlackMetalKhold),
            AppTheme::CoffeeTheme => Theme::new(CoffeeTheme),
            AppTheme::Japanesque => Theme::new(Japanesque),
            AppTheme::BlackMetalBurzum => Theme::new(BlackMetalBurzum),
            AppTheme::LiquidCarbonTransparent => Theme::new(LiquidCarbonTransparent),
            AppTheme::Darkmatrix => Theme::new(Darkmatrix),
            AppTheme::Vimbones => Theme::new(Vimbones),
            AppTheme::SolarizedDarkHigherContrast => Theme::new(SolarizedDarkHigherContrast),
            AppTheme::DimmedMonokai => Theme::new(DimmedMonokai),
            AppTheme::IrBlack => Theme::new(IrBlack),
            AppTheme::Pro => Theme::new(Pro),
            AppTheme::MonaLisa => Theme::new(MonaLisa),
            AppTheme::IcOrangePpl => Theme::new(IcOrangePpl),
            AppTheme::Wilmersdorf => Theme::new(Wilmersdorf),
            AppTheme::RaycastLight => Theme::new(RaycastLight),
            AppTheme::CobaltNextMinimal => Theme::new(CobaltNextMinimal),
            AppTheme::CatppuccinMacchiato => Theme::new(CatppuccinMacchiato),
            AppTheme::Oxocarbon => Theme::new(Oxocarbon),
            AppTheme::FishTank => Theme::new(FishTank),
            AppTheme::BuiltinSolarizedDark => Theme::new(BuiltinSolarizedDark),
            AppTheme::Andromeda => Theme::new(Andromeda),
            AppTheme::SnazzySoft => Theme::new(SnazzySoft),
            AppTheme::Vercel => Theme::new(Vercel),
            AppTheme::NordLight => Theme::new(NordLight),
            AppTheme::BuiltinPastelDark => Theme::new(BuiltinPastelDark),
            AppTheme::TomorrowNightEighties => Theme::new(TomorrowNightEighties),
            AppTheme::OneHalfLight => Theme::new(OneHalfLight),
            AppTheme::BlackMetalVenom => Theme::new(BlackMetalVenom),
            AppTheme::HorizonBright => Theme::new(HorizonBright),
            AppTheme::TangoHalfAdapted => Theme::new(TangoHalfAdapted),
            AppTheme::MaterialDarker => Theme::new(MaterialDarker),
            AppTheme::EmbersDark => Theme::new(EmbersDark),
            AppTheme::Violite => Theme::new(Violite),
            AppTheme::MonokaiProMachine => Theme::new(MonokaiProMachine),
            AppTheme::Encom => Theme::new(Encom),
            AppTheme::Embark => Theme::new(Embark),
            AppTheme::Ocean => Theme::new(Ocean),
            AppTheme::Batman => Theme::new(Batman),
            AppTheme::RedPlanet => Theme::new(RedPlanet),
            AppTheme::AppleSystemColors => Theme::new(AppleSystemColors),
            AppTheme::AppleSystemColorsLight => Theme::new(AppleSystemColorsLight),
            AppTheme::MonokaiProOctagon => Theme::new(MonokaiProOctagon),
            AppTheme::ThayerBright => Theme::new(ThayerBright),
            AppTheme::DarkPastel => Theme::new(DarkPastel),
            AppTheme::BlulocoLight => Theme::new(BlulocoLight),
            AppTheme::EverforestLightMed => Theme::new(EverforestLightMed),
            AppTheme::LaterThisEvening => Theme::new(LaterThisEvening),
            AppTheme::FlexokiLight => Theme::new(FlexokiLight),
            AppTheme::Darkside => Theme::new(Darkside),
            AppTheme::Harper => Theme::new(Harper),
            AppTheme::AtomOneLight => Theme::new(AtomOneLight),
            AppTheme::MaterialDesignColors => Theme::new(MaterialDesignColors),
            AppTheme::Adwaita => Theme::new(Adwaita),
            AppTheme::FirefoxDev => Theme::new(FirefoxDev),
            AppTheme::Kibble => Theme::new(Kibble),
            AppTheme::Duckbones => Theme::new(Duckbones),
            AppTheme::Hopscotch => Theme::new(Hopscotch),
            AppTheme::FarmhouseLight => Theme::new(FarmhouseLight),
            AppTheme::Srcery => Theme::new(Srcery),
            AppTheme::Flat => Theme::new(Flat),
            AppTheme::Subliminal => Theme::new(Subliminal),
            AppTheme::Kanagawabones => Theme::new(Kanagawabones),
            AppTheme::AlienBlood => Theme::new(AlienBlood),
            AppTheme::SelenizedDark => Theme::new(SelenizedDark),
            AppTheme::FlexokiDark => Theme::new(FlexokiDark),
            AppTheme::UltraDark => Theme::new(UltraDark),
            AppTheme::BananaBlueberry => Theme::new(BananaBlueberry),
            AppTheme::Elegant => Theme::new(Elegant),
            AppTheme::CyberpunkScarletProtocol => Theme::new(CyberpunkScarletProtocol),
            AppTheme::RosePineMoon => Theme::new(RosePineMoon),
            AppTheme::Wombat => Theme::new(Wombat),
            AppTheme::GruvboxMaterial => Theme::new(GruvboxMaterial),
            AppTheme::Sugarplum => Theme::new(Sugarplum),
            AppTheme::Medallion => Theme::new(Medallion),
            AppTheme::SeoulbonesLight => Theme::new(SeoulbonesLight),
            AppTheme::IrixTerminal => Theme::new(IrixTerminal),
            AppTheme::Vaughn => Theme::new(Vaughn),
            AppTheme::MonokaiProLight => Theme::new(MonokaiProLight),
            AppTheme::ParaisoDark => Theme::new(ParaisoDark),
            AppTheme::SleepyHollow => Theme::new(SleepyHollow),
            AppTheme::Monokai => Theme::new(Monokai),
            AppTheme::Argonaut => Theme::new(Argonaut),
            AppTheme::Catppuccin => Theme::new(Catppuccin),
            AppTheme::TokyoNight => Theme::new(TokyoNight),
            AppTheme::Terminal => Theme::new(Terminal),
            AppTheme::Chakra => Theme::new(Chakra),
            AppTheme::Config => Theme::new(Custom::default()),
            AppTheme::Tokyonight => todo!(),
        }
    }
}

impl Styler for Theme {
    fn table_header(&self) -> Style {
        self.styler().table_header()
    }

    fn row(&self, row: usize) -> Style {
        self.styler().row(row)
    }

    fn row_highlighted(&self) -> Style {
        self.styler().row_highlighted()
    }

    fn header(&self, col: usize) -> Style {
        self.styler().header(col)
    }

    fn tag(&self, col: usize) -> Style {
        self.styler().tag(col)
    }

    fn block(&self) -> Style {
        self.styler().block()
    }

    fn block_tag(&self) -> Style {
        self.styler().block_tag()
    }

    fn text(&self) -> Style {
        self.styler().text()
    }

    fn subtext(&self) -> Style {
        self.styler().subtext()
    }

    fn error(&self) -> Style {
        self.styler().error()
    }

    fn graph(&self, idx: usize) -> Style {
        self.styler().graph(idx)
    }

    fn id(&self) -> &str {
        if let Some(inner) = self.styler.as_ref() {
            inner.id()
        } else {
            "monokai"
        }
    }

    fn title(&self) -> &str {
        if let Some(inner) = self.styler.as_ref() {
            inner.title()
        } else {
            "Monokai"
        }
    }

    fn text_highlighted(&self) -> Style {
        self.styler().text_highlighted()
    }
}

impl PartialEq for Theme {
    fn eq(&self, other: &Self) -> bool {
        self.styler().id() == other.styler().id()
    }
}

impl Eq for Theme {}

impl Serialize for Theme {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.id())
    }
}

impl<'de> Deserialize<'de> for Theme {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let theme_str = String::deserialize(deserializer)?;
        match theme_str.as_str() {
            "monokai_pro_light_sun" => Ok(Theme::new(MonokaiProLightSun)),
            "black_metal_immortal_" => Ok(Theme::new(BlackMetalImmortal)),
            "starlight" => Ok(Theme::new(Starlight)),
            "ayu_light" => Ok(Theme::new(AyuLight)),
            "builtin_tango_light" => Ok(Theme::new(BuiltinTangoLight)),
            "nvim_light" => Ok(Theme::new(NvimLight)),
            "twilight" => Ok(Theme::new(Twilight)),
            "hybrid" => Ok(Theme::new(Hybrid)),
            "lovelace" => Ok(Theme::new(Lovelace)),
            "spring" => Ok(Theme::new(Spring)),
            "zenwritten_dark" => Ok(Theme::new(ZenwrittenDark)),
            "neopolitan" => Ok(Theme::new(Neopolitan)),
            "ciapre" => Ok(Theme::new(Ciapre)),
            "sublette" => Ok(Theme::new(Sublette)),
            "man_page" => Ok(Theme::new(ManPage)),
            "purplepeter" => Ok(Theme::new(Purplepeter)),
            "breadog" => Ok(Theme::new(Breadog)),
            "light_owl" => Ok(Theme::new(LightOwl)),
            "galizur" => Ok(Theme::new(Galizur)),
            "rose_pine" => Ok(Theme::new(RosePine)),
            "molokai" => Ok(Theme::new(Molokai)),
            "shaman" => Ok(Theme::new(Shaman)),
            "darkermatrix" => Ok(Theme::new(Darkermatrix)),
            "jackie_brown" => Ok(Theme::new(JackieBrown)),
            "espresso" => Ok(Theme::new(Espresso)),
            "peppermint" => Ok(Theme::new(Peppermint)),
            "ultra_violent" => Ok(Theme::new(UltraViolent)),
            "primary" => Ok(Theme::new(Primary)),
            "nvim_dark" => Ok(Theme::new(NvimDark)),
            "retro_legends" => Ok(Theme::new(RetroLegends)),
            "iceberg_dark" => Ok(Theme::new(IcebergDark)),
            "monokai_remastered" => Ok(Theme::new(MonokaiRemastered)),
            "dot_gov" => Ok(Theme::new(DotGov)),
            "oceanic_next" => Ok(Theme::new(OceanicNext)),
            "material" => Ok(Theme::new(Material)),
            "black_metal_marduk_" => Ok(Theme::new(BlackMetalMarduk)),
            "grey_green" => Ok(Theme::new(GreyGreen)),
            "broadcast" => Ok(Theme::new(Broadcast)),
            "matrix" => Ok(Theme::new(Matrix)),
            "one_double_light" => Ok(Theme::new(OneDoubleLight)),
            "electron_highlighter" => Ok(Theme::new(ElectronHighlighter)),
            "ubuntu" => Ok(Theme::new(Ubuntu)),
            "clrs" => Ok(Theme::new(Clrs)),
            "tomorrow_night_blue" => Ok(Theme::new(TomorrowNightBlue)),
            "django" => Ok(Theme::new(Django)),
            "brogrammer" => Ok(Theme::new(Brogrammer)),
            "mellow" => Ok(Theme::new(Mellow)),
            "jet_brains_darcula" => Ok(Theme::new(JetbrainsDarcula)),
            "monokai_vivid" => Ok(Theme::new(MonokaiVivid)),
            "fideloper" => Ok(Theme::new(Fideloper)),
            "farmhouse_dark" => Ok(Theme::new(FarmhouseDark)),
            "royal" => Ok(Theme::new(Royal)),
            "gruvbox_light" => Ok(Theme::new(GruvboxLight)),
            "gruvbox_dark" => Ok(Theme::new(GruvboxDark)),
            "smyck" => Ok(Theme::new(Smyck)),
            "pnevma" => Ok(Theme::new(Pnevma)),
            "black_metal_nile_" => Ok(Theme::new(BlackMetalNile)),
            "elementary" => Ok(Theme::new(Elementary)),
            "squirrelsong_dark" => Ok(Theme::new(SquirrelsongDark)),
            "catppuccin_mocha" => Ok(Theme::new(CatppuccinMocha)),
            "black_metal_bathory_" => Ok(Theme::new(BlackMetalBathory)),
            "liquid_carbon_transparent_inverse" => Ok(Theme::new(LiquidCarbonTransparentInverse)),
            "fun_forrest" => Ok(Theme::new(FunForrest)),
            "arcoiris" => Ok(Theme::new(Arcoiris)),
            "desert" => Ok(Theme::new(Desert)),
            "doom_one" => Ok(Theme::new(DoomOne)),
            "spacegray_eighties" => Ok(Theme::new(SpacegrayEighties)),
            "warm_neon" => Ok(Theme::new(WarmNeon)),
            "dimidium" => Ok(Theme::new(Dimidium)),
            "git_lab_dark_grey" => Ok(Theme::new(GitlabDarkGrey)),
            "cyberpunk" => Ok(Theme::new(Cyberpunk)),
            "tearout" => Ok(Theme::new(Tearout)),
            "aura" => Ok(Theme::new(Aura)),
            "grape" => Ok(Theme::new(Grape)),
            "selenized_light" => Ok(Theme::new(SelenizedLight)),
            "blazer" => Ok(Theme::new(Blazer)),
            "kanagawa_dragon" => Ok(Theme::new(KanagawaDragon)),
            "hurtado" => Ok(Theme::new(Hurtado)),
            "material_ocean" => Ok(Theme::new(MaterialOcean)),
            "xcode_dark_hc" => Ok(Theme::new(XcodeDarkHc)),
            "citruszest" => Ok(Theme::new(Citruszest)),
            "crayon_pony_fish" => Ok(Theme::new(CrayonPonyFish)),
            "relaxed" => Ok(Theme::new(Relaxed)),
            "rapture" => Ok(Theme::new(Rapture)),
            "black_metal_gorgoroth_" => Ok(Theme::new(BlackMetalGorgoroth)),
            "cyberdyne" => Ok(Theme::new(Cyberdyne)),
            "git_lab_light" => Ok(Theme::new(GitlabLight)),
            "iceberg_light" => Ok(Theme::new(IcebergLight)),
            "floraverse" => Ok(Theme::new(Floraverse)),
            "atom_one_dark" => Ok(Theme::new(AtomOneDark)),
            "shades_of_purple" => Ok(Theme::new(ShadesOfPurple)),
            "wez" => Ok(Theme::new(Wez)),
            "ayu_mirage" => Ok(Theme::new(AyuMirage)),
            "obsidian" => Ok(Theme::new(Obsidian)),
            "kolorit" => Ok(Theme::new(Kolorit)),
            "hivacruz" => Ok(Theme::new(Hivacruz)),
            "adwaita_dark" => Ok(Theme::new(AdwaitaDark)),
            "pencil_light" => Ok(Theme::new(PencilLight)),
            "bluloco_dark" => Ok(Theme::new(BlulocoDark)),
            "builtin_tango_dark" => Ok(Theme::new(BuiltinTangoDark)),
            "belafonte_day" => Ok(Theme::new(BelafonteDay)),
            "blue_dolphin" => Ok(Theme::new(BlueDolphin)),
            "monokai_pro" => Ok(Theme::new(MonokaiPro)),
            "the_hulk" => Ok(Theme::new(TheHulk)),
            "synthwave" => Ok(Theme::new(Synthwave)),
            "konsolas" => Ok(Theme::new(Konsolas)),
            "dayfox" => Ok(Theme::new(Dayfox)),
            "solarized_darcula" => Ok(Theme::new(SolarizedDarcula)),
            "nord_wave" => Ok(Theme::new(NordWave)),
            "urple" => Ok(Theme::new(Urple)),
            "xcode_light_hc" => Ok(Theme::new(XcodeLightHc)),
            "tokyo_night_night" => Ok(Theme::new(TokyoNightNight)),
            "synthwave_alpha" => Ok(Theme::new(SynthwaveAlpha)),
            "espresso_libre" => Ok(Theme::new(EspressoLibre)),
            "git_hub_dark_default" => Ok(Theme::new(GithubDarkDefault)),
            "breeze" => Ok(Theme::new(Breeze)),
            "fahrenheit" => Ok(Theme::new(Fahrenheit)),
            "catppuccin_latte" => Ok(Theme::new(CatppuccinLatte)),
            "miasma" => Ok(Theme::new(Miasma)),
            "everforest_dark_hard" => Ok(Theme::new(EverforestDarkHard)),
            "seti" => Ok(Theme::new(Seti)),
            "black_metal_dark_funeral_" => Ok(Theme::new(BlackMetalDarkFuneral)),
            "zenburned" => Ok(Theme::new(Zenburned)),
            "cobalt_next_dark" => Ok(Theme::new(CobaltNextDark)),
            "django_reborn_again" => Ok(Theme::new(DjangoRebornAgain)),
            "treehouse" => Ok(Theme::new(Treehouse)),
            "mariana" => Ok(Theme::new(Mariana)),
            "retro" => Ok(Theme::new(Retro)),
            "cursor_dark" => Ok(Theme::new(CursorDark)),
            "hardcore" => Ok(Theme::new(Hardcore)),
            "neon" => Ok(Theme::new(Neon)),
            "git_lab_dark" => Ok(Theme::new(GitlabDark)),
            "under_the_sea" => Ok(Theme::new(UnderTheSea)),
            "violet_light" => Ok(Theme::new(VioletLight)),
            "ayu" => Ok(Theme::new(Ayu)),
            "havn_skumring" => Ok(Theme::new(HavnSkumring)),
            "afterglow" => Ok(Theme::new(Afterglow)),
            "doom_peacock" => Ok(Theme::new(DoomPeacock)),
            "apple_classic" => Ok(Theme::new(AppleClassic)),
            "vibrant_ink" => Ok(Theme::new(VibrantInk)),
            "arthur" => Ok(Theme::new(Arthur)),
            "tinacious_design_light" => Ok(Theme::new(TinaciousDesignLight)),
            "wild_cherry" => Ok(Theme::new(WildCherry)),
            "hipster_green" => Ok(Theme::new(HipsterGreen)),
            "mathias" => Ok(Theme::new(Mathias)),
            "neobones_dark" => Ok(Theme::new(NeobonesDark)),
            "spacegray_eighties_dull" => Ok(Theme::new(SpacegrayEightiesDull)),
            "night_owlish_light" => Ok(Theme::new(NightOwlishLight)),
            "chester" => Ok(Theme::new(Chester)),
            "pandora" => Ok(Theme::new(Pandora)),
            "ghostty_default_style_dark" => Ok(Theme::new(GhosttyDefaultStyleDark)),
            "one_double_dark" => Ok(Theme::new(OneDoubleDark)),
            "zenbones_light" => Ok(Theme::new(ZenbonesLight)),
            "niji" => Ok(Theme::new(Niji)),
            "pro_light" => Ok(Theme::new(ProLight)),
            "spacegray_bright" => Ok(Theme::new(SpacegrayBright)),
            "sea_shells" => Ok(Theme::new(SeaShells)),
            "vague" => Ok(Theme::new(Vague)),
            "tokyo_night_moon" => Ok(Theme::new(TokyoNightMoon)),
            "xcode_light" => Ok(Theme::new(XcodeLight)),
            "aardvark_blue" => Ok(Theme::new(AardvarkBlue)),
            "zenwritten_light" => Ok(Theme::new(ZenwrittenLight)),
            "cobalt_neon" => Ok(Theme::new(CobaltNeon)),
            "duotone_dark" => Ok(Theme::new(DuotoneDark)),
            "cga" => Ok(Theme::new(Cga)),
            "idea" => Ok(Theme::new(Idea)),
            "synthwave_everything" => Ok(Theme::new(SynthwaveEverything)),
            "black_metal" => Ok(Theme::new(BlackMetal)),
            "havn_daggry" => Ok(Theme::new(HavnDaggry)),
            "git_hub" => Ok(Theme::new(Github)),
            "seafoam_pastel" => Ok(Theme::new(SeafoamPastel)),
            "chalkboard" => Ok(Theme::new(Chalkboard)),
            "elemental" => Ok(Theme::new(Elemental)),
            "novel" => Ok(Theme::new(Novel)),
            "snazzy" => Ok(Theme::new(Snazzy)),
            "monokai_classic" => Ok(Theme::new(MonokaiClassic)),
            "zenburn" => Ok(Theme::new(Zenburn)),
            "git_hub_light_default" => Ok(Theme::new(GithubLightDefault)),
            "laser" => Ok(Theme::new(Laser)),
            "birds_of_paradise" => Ok(Theme::new(BirdsOfParadise)),
            "mellifluous" => Ok(Theme::new(Mellifluous)),
            "fairyfloss" => Ok(Theme::new(Fairyfloss)),
            "night_owl" => Ok(Theme::new(NightOwl)),
            "one_half_dark" => Ok(Theme::new(OneHalfDark)),
            "firefly_traditional" => Ok(Theme::new(FireflyTraditional)),
            "terafox" => Ok(Theme::new(Terafox)),
            "rose_pine_dawn" => Ok(Theme::new(RosePineDawn)),
            "sundried" => Ok(Theme::new(Sundried)),
            "tokyo_night_storm" => Ok(Theme::new(TokyoNightStorm)),
            "nord" => Ok(Theme::new(Nord)),
            "piatto_light" => Ok(Theme::new(PiattoLight)),
            "abernathy" => Ok(Theme::new(Abernathy)),
            "tokyo_night_day" => Ok(Theme::new(TokyoNightDay)),
            "powershell" => Ok(Theme::new(Powershell)),
            "jellybeans" => Ok(Theme::new(Jellybeans)),
            "blue_matrix" => Ok(Theme::new(BlueMatrix)),
            "sonokai" => Ok(Theme::new(Sonokai)),
            "tomorrow_night_burns" => Ok(Theme::new(TomorrowNightBurns)),
            "sakura" => Ok(Theme::new(Sakura)),
            "raycast_dark" => Ok(Theme::new(RaycastDark)),
            "kanagawa_wave" => Ok(Theme::new(KanagawaWave)),
            "cutie_pro" => Ok(Theme::new(CutiePro)),
            "horizon" => Ok(Theme::new(Horizon)),
            "spiderman" => Ok(Theme::new(Spiderman)),
            "black_metal_mayhem_" => Ok(Theme::new(BlackMetalMayhem)),
            "kitty_default" => Ok(Theme::new(KittyDefault)),
            "idle_toes" => Ok(Theme::new(IdleToes)),
            "terminal_basic_dark" => Ok(Theme::new(TerminalBasicDark)),
            "framer" => Ok(Theme::new(Framer)),
            "moonfly" => Ok(Theme::new(Moonfly)),
            "monokai_soda" => Ok(Theme::new(MonokaiSoda)),
            "slate" => Ok(Theme::new(Slate)),
            "firewatch" => Ok(Theme::new(Firewatch)),
            "spacegray" => Ok(Theme::new(Spacegray)),
            "symfonic" => Ok(Theme::new(Symfonic)),
            "spacedust" => Ok(Theme::new(Spacedust)),
            "teerb" => Ok(Theme::new(Teerb)),
            "rippedcasts" => Ok(Theme::new(Rippedcasts)),
            "tomorrow_night_bright" => Ok(Theme::new(TomorrowNightBright)),
            "chalk" => Ok(Theme::new(Chalk)),
            "heeler" => Ok(Theme::new(Heeler)),
            "alabaster" => Ok(Theme::new(Alabaster)),
            "galaxy" => Ok(Theme::new(Galaxy)),
            "adventure" => Ok(Theme::new(Adventure)),
            "git_hub_light_high_contrast" => Ok(Theme::new(GithubLightHighContrast)),
            "unikitty" => Ok(Theme::new(Unikitty)),
            "lavandula" => Ok(Theme::new(Lavandula)),
            "tinacious_design_dark" => Ok(Theme::new(TinaciousDesignDark)),
            "flatland" => Ok(Theme::new(Flatland)),
            "git_hub_light_colorblind" => Ok(Theme::new(GithubLightColorblind)),
            "challenger_deep" => Ok(Theme::new(ChallengerDeep)),
            "mirage" => Ok(Theme::new(Mirage)),
            "deep" => Ok(Theme::new(Deep)),
            "vesper" => Ok(Theme::new(Vesper)),
            "aurora" => Ok(Theme::new(Aurora)),
            "jubi" => Ok(Theme::new(Jubi)),
            "calamity" => Ok(Theme::new(Calamity)),
            "neutron" => Ok(Theme::new(Neutron)),
            "red_alert" => Ok(Theme::new(RedAlert)),
            "material_dark" => Ok(Theme::new(MaterialDark)),
            "everblush" => Ok(Theme::new(Everblush)),
            "kurokula" => Ok(Theme::new(Kurokula)),
            "solarized_osaka_night" => Ok(Theme::new(SolarizedOsakaNight)),
            "pale_night_hc" => Ok(Theme::new(PaleNightHc)),
            "ardoise" => Ok(Theme::new(Ardoise)),
            "monokai_pro_spectrum" => Ok(Theme::new(MonokaiProSpectrum)),
            "gruber_darker" => Ok(Theme::new(GruberDarker)),
            "git_hub_dark" => Ok(Theme::new(GithubDark)),
            "solarized_dark_patched" => Ok(Theme::new(SolarizedDarkPatched)),
            "melange_light" => Ok(Theme::new(MelangeLight)),
            "hacktober" => Ok(Theme::new(Hacktober)),
            "ic_green_ppl" => Ok(Theme::new(IcGreenPpl)),
            "operator_mono_dark" => Ok(Theme::new(OperatorMonoDark)),
            "tomorrow_night" => Ok(Theme::new(TomorrowNight)),
            "homebrew" => Ok(Theme::new(Homebrew)),
            "wryan" => Ok(Theme::new(Wryan)),
            "git_hub_dark_colorblind" => Ok(Theme::new(GithubDarkColorblind)),
            "borland" => Ok(Theme::new(Borland)),
            "red_sands" => Ok(Theme::new(RedSands)),
            "rebecca" => Ok(Theme::new(Rebecca)),
            "terminal_basic" => Ok(Theme::new(TerminalBasic)),
            "dracula" => Ok(Theme::new(Dracula)),
            "nightfox" => Ok(Theme::new(Nightfox)),
            "builtin_light" => Ok(Theme::new(BuiltinLight)),
            "builtin_solarized_light" => Ok(Theme::new(BuiltinSolarizedLight)),
            "glacier" => Ok(Theme::new(Glacier)),
            "catppuccin_frappe" => Ok(Theme::new(CatppuccinFrappe)),
            "forest_blue" => Ok(Theme::new(ForestBlue)),
            "builtin_dark" => Ok(Theme::new(BuiltinDark)),
            "whimsy" => Ok(Theme::new(Whimsy)),
            "xcode_dark" => Ok(Theme::new(XcodeDark)),
            "gruvbox_dark_hard" => Ok(Theme::new(GruvboxDarkHard)),
            "ryuuko" => Ok(Theme::new(Ryuuko)),
            "django_smooth" => Ok(Theme::new(DjangoSmooth)),
            "violet_dark" => Ok(Theme::new(VioletDark)),
            "purple_rain" => Ok(Theme::new(PurpleRain)),
            "square" => Ok(Theme::new(Square)),
            "seoulbones_dark" => Ok(Theme::new(SeoulbonesDark)),
            "tokyo_night" => Ok(Theme::new(TokyoNight)),
            "dark_modern" => Ok(Theme::new(DarkModern)),
            "monokai_pro_ristretto" => Ok(Theme::new(MonokaiProRistretto)),
            "irix_console" => Ok(Theme::new(IrixConsole)),
            "melange_dark" => Ok(Theme::new(MelangeDark)),
            "earthsong" => Ok(Theme::new(Earthsong)),
            "liquid_carbon" => Ok(Theme::new(LiquidCarbon)),
            "gruvbox_light_hard" => Ok(Theme::new(GruvboxLightHard)),
            "adventure_time" => Ok(Theme::new(AdventureTime)),
            "phala_green_dark" => Ok(Theme::new(PhalaGreenDark)),
            "soft_server" => Ok(Theme::new(SoftServer)),
            "pencil_dark" => Ok(Theme::new(PencilDark)),
            "front_end_delight" => Ok(Theme::new(FrontEndDelight)),
            "grass" => Ok(Theme::new(Grass)),
            "ollie" => Ok(Theme::new(Ollie)),
            "midnight_in_mojave" => Ok(Theme::new(MidnightInMojave)),
            "highway" => Ok(Theme::new(Highway)),
            "overnight_slumber" => Ok(Theme::new(OvernightSlumber)),
            "belafonte_night" => Ok(Theme::new(BelafonteNight)),
            "tango_adapted" => Ok(Theme::new(TangoAdapted)),
            "blue_berry_pie" => Ok(Theme::new(BlueBerryPie)),
            "tomorrow" => Ok(Theme::new(Tomorrow)),
            "scarlet_protocol" => Ok(Theme::new(ScarletProtocol)),
            "kitty_low_contrast" => Ok(Theme::new(KittyLowContrast)),
            "oceanic_material" => Ok(Theme::new(OceanicMaterial)),
            "guezwhoz" => Ok(Theme::new(Guezwhoz)),
            "xcode_wwdc" => Ok(Theme::new(XcodeWwdc)),
            "toy_chest" => Ok(Theme::new(ToyChest)),
            "popping_and_locking" => Ok(Theme::new(PoppingAndLocking)),
            "neobones_light" => Ok(Theme::new(NeobonesLight)),
            "atelier_sulphurpool" => Ok(Theme::new(AtelierSulphurpool)),
            "cobalt_next" => Ok(Theme::new(CobaltNext)),
            "atom" => Ok(Theme::new(Atom)),
            "zenbones_dark" => Ok(Theme::new(ZenbonesDark)),
            "zenbones" => Ok(Theme::new(Zenbones)),
            "bright_lights" => Ok(Theme::new(BrightLights)),
            "git_hub_dark_high_contrast" => Ok(Theme::new(GithubDarkHighContrast)),
            "paul_millr" => Ok(Theme::new(PaulMillr)),
            "nocturnal_winter" => Ok(Theme::new(NocturnalWinter)),
            "lab_fox" => Ok(Theme::new(LabFox)),
            "git_hub_dark_dimmed" => Ok(Theme::new(GithubDarkDimmed)),
            "detuned" => Ok(Theme::new(Detuned)),
            "misterioso" => Ok(Theme::new(Misterioso)),
            "black_metal_khold_" => Ok(Theme::new(BlackMetalKhold)),
            "coffee_theme" => Ok(Theme::new(CoffeeTheme)),
            "japanesque" => Ok(Theme::new(Japanesque)),
            "black_metal_burzum_" => Ok(Theme::new(BlackMetalBurzum)),
            "liquid_carbon_transparent" => Ok(Theme::new(LiquidCarbonTransparent)),
            "darkmatrix" => Ok(Theme::new(Darkmatrix)),
            "vimbones" => Ok(Theme::new(Vimbones)),
            "solarized_dark_higher_contrast" => Ok(Theme::new(SolarizedDarkHigherContrast)),
            "dimmed_monokai" => Ok(Theme::new(DimmedMonokai)),
            "ir_black" => Ok(Theme::new(IrBlack)),
            "pro" => Ok(Theme::new(Pro)),
            "mona_lisa" => Ok(Theme::new(MonaLisa)),
            "ic_orange_ppl" => Ok(Theme::new(IcOrangePpl)),
            "wilmersdorf" => Ok(Theme::new(Wilmersdorf)),
            "raycast_light" => Ok(Theme::new(RaycastLight)),
            "cobalt_next_minimal" => Ok(Theme::new(CobaltNextMinimal)),
            "catppuccin_macchiato" => Ok(Theme::new(CatppuccinMacchiato)),
            "oxocarbon" => Ok(Theme::new(Oxocarbon)),
            "fish_tank" => Ok(Theme::new(FishTank)),
            "builtin_solarized_dark" => Ok(Theme::new(BuiltinSolarizedDark)),
            "andromeda" => Ok(Theme::new(Andromeda)),
            "snazzy_soft" => Ok(Theme::new(SnazzySoft)),
            "vercel" => Ok(Theme::new(Vercel)),
            "nord_light" => Ok(Theme::new(NordLight)),
            "builtin_pastel_dark" => Ok(Theme::new(BuiltinPastelDark)),
            "tomorrow_night_eighties" => Ok(Theme::new(TomorrowNightEighties)),
            "one_half_light" => Ok(Theme::new(OneHalfLight)),
            "black_metal_venom_" => Ok(Theme::new(BlackMetalVenom)),
            "horizon_bright" => Ok(Theme::new(HorizonBright)),
            "tango_half_adapted" => Ok(Theme::new(TangoHalfAdapted)),
            "material_darker" => Ok(Theme::new(MaterialDarker)),
            "embers_dark" => Ok(Theme::new(EmbersDark)),
            "violite" => Ok(Theme::new(Violite)),
            "monokai_pro_machine" => Ok(Theme::new(MonokaiProMachine)),
            "encom" => Ok(Theme::new(Encom)),
            "embark" => Ok(Theme::new(Embark)),
            "ocean" => Ok(Theme::new(Ocean)),
            "batman" => Ok(Theme::new(Batman)),
            "red_planet" => Ok(Theme::new(RedPlanet)),
            "apple_system_colors" => Ok(Theme::new(AppleSystemColors)),
            "apple_system_colors_light" => Ok(Theme::new(AppleSystemColorsLight)),
            "monokai_pro_octagon" => Ok(Theme::new(MonokaiProOctagon)),
            "thayer_bright" => Ok(Theme::new(ThayerBright)),
            "dark_pastel" => Ok(Theme::new(DarkPastel)),
            "bluloco_light" => Ok(Theme::new(BlulocoLight)),
            "everforest_light_med" => Ok(Theme::new(EverforestLightMed)),
            "later_this_evening" => Ok(Theme::new(LaterThisEvening)),
            "flexoki_light" => Ok(Theme::new(FlexokiLight)),
            "darkside" => Ok(Theme::new(Darkside)),
            "harper" => Ok(Theme::new(Harper)),
            "atom_one_light" => Ok(Theme::new(AtomOneLight)),
            "material_design_colors" => Ok(Theme::new(MaterialDesignColors)),
            "adwaita" => Ok(Theme::new(Adwaita)),
            "firefox_dev" => Ok(Theme::new(FirefoxDev)),
            "kibble" => Ok(Theme::new(Kibble)),
            "duckbones" => Ok(Theme::new(Duckbones)),
            "hopscotch" => Ok(Theme::new(Hopscotch)),
            "farmhouse_light" => Ok(Theme::new(FarmhouseLight)),
            "srcery" => Ok(Theme::new(Srcery)),
            "flat" => Ok(Theme::new(Flat)),
            "subliminal" => Ok(Theme::new(Subliminal)),
            "kanagawabones" => Ok(Theme::new(Kanagawabones)),
            "alien_blood" => Ok(Theme::new(AlienBlood)),
            "selenized_dark" => Ok(Theme::new(SelenizedDark)),
            "flexoki_dark" => Ok(Theme::new(FlexokiDark)),
            "ultra_dark" => Ok(Theme::new(UltraDark)),
            "banana_blueberry" => Ok(Theme::new(BananaBlueberry)),
            "elegant" => Ok(Theme::new(Elegant)),
            "cyberpunk_scarlet_protocol" => Ok(Theme::new(CyberpunkScarletProtocol)),
            "rose_pine_moon" => Ok(Theme::new(RosePineMoon)),
            "wombat" => Ok(Theme::new(Wombat)),
            "gruvbox_material" => Ok(Theme::new(GruvboxMaterial)),
            "sugarplum" => Ok(Theme::new(Sugarplum)),
            "medallion" => Ok(Theme::new(Medallion)),
            "seoulbones_light" => Ok(Theme::new(SeoulbonesLight)),
            "irix_terminal" => Ok(Theme::new(IrixTerminal)),
            "vaughn" => Ok(Theme::new(Vaughn)),
            "monokai_pro_light" => Ok(Theme::new(MonokaiProLight)),
            "paraiso_dark" => Ok(Theme::new(ParaisoDark)),
            "sleepy_hollow" => Ok(Theme::new(SleepyHollow)),
            "monokai" => Ok(Theme::new(Monokai)),
            "argonaut" => Ok(Theme::new(Argonaut)),
            "terminal" => Ok(Theme::new(Terminal)),
            "catppuccin" => Ok(Theme::new(Catppuccin)),
            "tokyo-night" => Ok(Theme::new(TokyoNight)),
            "chakra" => Ok(Theme::new(Chakra)),
            "custom" => Ok(Theme::new(
                Custom::read_from_config_dir().unwrap_or_default(),
            )),
            _ => Err(serde::de::Error::custom(format!(
                "Unknown theme: {}",
                theme_str
            ))),
        }
    }
}
